language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: GvkHsCcvxOgYfrkEDNvy3Byte9XfnrjlkecWfUCCU50KtUfKZJjZFrPHoyvI4HNYWTa0Eq/x9GFUwHO+LYGw4/dmLle45Cu7GYTMMWNEd/FCQdrYN8X9F6DHBy8ABltmmK+mc0UEJR1nHxB4nxZopybvWMWsS+c5dHPy5BlEEoe44dEy14o+3lFEHD4/PcRxwiM/8NbfF3oYHr7lkwGZPH12dYIz7SHETdjr3npqmphKSSlpe5YSWdtmnjBx56HrmgIjw/gvb7g/b3S5n1snfXjD2T7dm7nYMWTd/eiTPbHTLRHvX8fFQpP/o66cvCbS5SVk7+XWmAhhvT7/INhFYThOOEues/+FKweQ+tspYK8N3oSxLh6WxfkK6XOOWnlV/ZofzNDwNJ+8LsW14vh7x6B4TRkHMhrtuOpyVNkIdtrwpL2cIkEinR+72vPQ+ZNPWy/yl6+1J6xzAzuucmt/FSZO5S3hz8Kfgo68CtVW4weWpUik/13ovXsvctkxGFxO7sMz5OWcuUgLAOjQ4WOckRls06DdoJjtXmlQZUE5jWuluYmPFLFtFWnoha59QaTqJdV8rxfRdN7w9WiO/txJ2Bz/uxMTK/wkLZVoVe+VJOU185+dSXoyq+WY1JuffMmlPXQ56d18jfcvjX8XsQq+3dU/598/9TBOX8FNfdQuBT8=
  app: dry-ravine-94147
  on:
    repo: ASiede/ourtinerary-api
